name: push-dockerfile-image
on:
  push:
    branches: [main]
    workflow-dispatch:
jobs:
  updateDocker:
    runs-on: ubuntu-latest
      steps:
      - name: Login, build, and push
        uses: actions/checkout@v2
        env:
          USER: ${{ secrets.DOCKER_USERNAME }}
          PASS: ${{ secrets.DOCKER_TOKEN }}
         run: |
          docker login -u "$USER" -p "$PASS"
          docker build -t "$USER"/albright-ceg3120 .
          docker push "$USER"/albright-ceg3120
